### ISSUE TITLE
Need a name

### ISSUE THREAD

**Issue by TiddoLangerak** [Magnetme/YOLO#1]
@Magnetme/developers - This is going to be our replacement for browserify, but I'm still in need of a name. Any suggestions?

**Comment by alexnederlof** [comment]
- YACJS yet another common js 
- ThemModules.js

**Comment by wouterwillems10** [comment]
ModuLangerak

**Comment by alexnederlof** [comment]
yomodule.js

**Comment by wouterwillems10** [comment]
%js

**Comment by alexnederlof** [comment]
RCJSOP -> Resembles Commonjs on purpose

**Comment by alexnederlof** [comment]
BAC -> Bourne again common.js

**Comment by alexnederlof** [comment]
BINC -> Bink Is Not CommonJS

**Comment by wouterwillems10** [comment]
<img src="http://jimpunk.net/Loading/wp-content/uploads/loading45.gif" />JS

**Comment by TiddoLangerak** [comment]
bowerserify ![http://upload.wikimedia.org/wikipedia/en/e/ec/Bowser_-_New_Super_Mario_Bros_2.png](http://upload.wikimedia.org/wikipedia/en/e/ec/Bowser_-_New_Super_Mario_Bros_2.png)

**Comment by wouterwillems10** [comment]
GetALoadOfThis.js

**Comment by wouterwillems10** [comment]
deLaatsteLoadjes.js

**Comment by TiddoLangerak** [comment]
YOLO.js (you only load once)

**Comment by wouterwillems10** [comment]
jean cLoade van damme

**Comment by AlexKolpa** [comment]
The Loading Daylights

**Comment by wouterwillems10** [comment]
metDeBillenBload

**Comment by alexnederlof** [comment]
YOLO :+1:

**Comment by rogierslag** [comment]
![enough-internet](https://cloud.githubusercontent.com/assets/2778689/6153294/f9202c1c-b223-11e4-8b9b-e227e497e668.gif)

**Comment by TiddoLangerak** [comment]
I will ship this today, I'll use YOLO as the project name, but since the npm name YOLO is already taken the package will be called `yolo-loader`

**Comment by rogierslag** [comment]
make it at least `yoloader` then

**Comment by TiddoLangerak** [comment]
I like.

**Comment by TiddoLangerak** [comment]
Or, like a good JS hipster, yoloadr (credits to @AlexKolpa )

**Comment by rogierslag** [comment]
as an extra tribute to the 9gag community `yoloadrp`
